version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_builds:
    commands:
      - npm ci
  builds:
    commands:
      - npm run build
artifacts:
  files:
    - start-server.sh
    - stop-serivce.sh
    - server.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'